### PR TITLE
Fix ssl certificate verification error issue#359

### PR DESCRIPTION
**Pull request by ldfsilva**
Add an option for not checking ssl certificate.
Please let me know if any additional changes are required in order to merge it.

### CODE REVIEW

**Comment by GhostofGoes** [comment]
Why not use SmartConnectNoSSL to disable SSL verification?

**Comment by ldfsilva** [comment]
I haven't thought on that @GhostofGoes, and I agree with you that using SmartConnectNoSSL will be a better solution.

I have changed it to make usage of that instead of building and passing a ssl context, take a look at 679a2ac .

**Comment by tianhao64** [comment]
@ldfsilva Thanks for the fix.

**Comment by thinksabin** [comment]
Thanks @ldfsilva 
-S did work for me.

I guess,  python ssl error while trying getallvms.py #359 can be tagged 'resolved' or something similar. 

thanks again

**Pull request merged**
