### PR TITLE
Sample to show how to create a snapshot.

### LINKED ISSUE #31: Sample: create a snapshot
Demonstrate how to make a snapshot given a running virtual machine.

### PR DESCRIPTION
**Pull request by michaelrice**
Fixes #31

### CODE REVIEW

**Comment by hartsock** [comment]
Hey @michaelrice. So, I'm seeing [this issue](https://travis-ci.org/vmware/pyvmomi-community-samples/builds/58836230) which I suppose @landscape-bot  has already commented on. I'll take a look at this in the next few days as I have time.

**Comment by michaelrice** [comment]
I fixed the bot issue of unused import. The only thing left is not in my
sample. Its Travis failing on the pep8 step from some of the other samples.

**Comment by hartsock** [comment]
@michaelrice hopefully someone can put in some time and fix those other pep8 problems? I'm swamped until Wednesday.

**Comment by michaelrice** [comment]
@hartsock I added the pep8 cleanup to #164 if you wan to merge it first Ill rebase this afterwords.

**Comment by michaelrice** [comment]
@hartsock I got this rebased but travis failed to activate the virtualenv somehow..

**Comment by michaelrice** [comment]
I confirmed with travis-ci support this issue is being caused by their infrastructure problem. They are getting ready to release a status update about it.

**Comment by hartsock** [comment]
@michaelrice thanks for keeping us in the loop on this!

**Comment by michaelrice** [comment]
@hartsock there is no way to re-trigger the job unless I push more.. so its kind of stuck like this. The only thing wrong before were pep8 issues with other samples which I fixed in #164 I could close this and reopen it or you could just merge it :dancers:

**Comment by hartsock** [comment]
I found a control to let me retrigger the CI loop... we should see new results [here](https://travis-ci.org/vmware/pyvmomi-community-samples/builds/59408403).

**Pull request merged**
