### PR TITLE
example for adding a disk to a VM

### LINKED ISSUE #15: Sample: create new VMDK and attach it to a VM
Show how to create a blank VMDK and attach it to an existing VM. Show how to make the VMDK *inside* the virtual machine's folder.

### PR DESCRIPTION
**Pull request by whereismyjetpack**
Example for adding a disk to an existing VM. fixes #15 I hope this helps someone.

### CODE REVIEW

**Comment by hartsock** [comment]
I'll review this in the next few working days.

**Comment by djcrabhat** [comment]
any idea on how to set a datastore for my newly created, additional drives?  Per https://github.com/vmware/pyvmomi/blob/master/docs/vim/vm/device/VirtualDevice/FileBackingInfo.rst , the place I'd naturually think it could be set is only for retrieving data, it is not used for configuration

**Comment by hartsock** [comment]
@djcrabhat it would probably be good to ask that as a new [issue](https://github.com/vmware/pyvmomi-community-samples/issues). I'm also not sure what context you mean. Do you mean new drives for the VM? new drive for the Guest? If you mean new drive for the Host, I'm not sure. There.

As I said my bandwidth is limited until we shake out a few things around vSphere 6.0 but here's something that might help:
* https://gist.github.com/hartsock/d8b9c56cd7f779c92a78

**Comment by djcrabhat** [comment]
That's very helpful, thank you.  It seems to work a different way, too.  If I set an appropriate fileName for the backing info ([DataStore] folder/name.vmdk), that puts the new disk on the right datastore.  But your way might be "more correct".  Thanks for the advice.

**Comment by hartsock** [comment]
Pulling for review...

**Comment by hartsock** [comment]
I should probably just edit this in place when I have a moment. This is 95% fine.

**Comment by Rathore2014** [comment]
For me it works if vm has at least one disk , in case of dummy vm with no disk fails saying variable "controller.key" referenced before assignment.

**Comment by noagr** [comment]
I tried to use this code to add existing RDM vmdk file that I have created with the command vmkfstools -z <disk> <new disk> but 
I am keep getting this error: "Invalid configuration for device '0'.",
I can link the new disk to the vm in the UI without any problem
Does anyone one have a clue?
cancelled = false,
   cancelable = false,
   error = (vim.fault.InvalidDeviceSpec) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      msg = "Invalid configuration for device '0'.",
      faultCause = <unset>,
      faultMessage = (vmodl.LocalizableMessage) [],
      property = u'VirtualDisk.controllerKey',
      deviceIndex = 0
   },

**Comment by whereismyjetpack** [comment]
In this example, the controllerkey is hard coded in, looks like on your vm the controllerkey is not 1000.

**Comment by noagr** [comment]
Thanks, But I calculated the controllerkey by: 
controller = None
devices = vm.config.hardware.device
for device in devices:
    if isinstance(device, vim.vm.device.VirtualSCSIController):
    controller = device
and from it I do:
virtual_disk = vim.vm.device.VirtualDisk()
...
virtual_disk.controllerKey = controller.key

Should I take a different controller?
Thanks

**Comment by Rathore2014** [comment]
I have similar issue, it only works for me if I have one existing disk.
I am getting error "controller.key" referenced before assignment.

**Comment by hartsock** [comment]
Attn @tianhao64

**Pull request merged**
