### PR TITLE
Sample for finding VMs that exist on datastore(s) but not in inventory

### PR DESCRIPTION
**Pull request by joshcoen**
added a sample for finding VMs that exist on datastore(s) but not in inv...

### CODE REVIEW

**Comment by joshcoen** [comment]
Changes made, let me know if there is anything else. Thanks and happy new year!

**Comment by hartsock** [comment]
@joshcoen I'm getting an [error](https://travis-ci.org/vmware/pyvmomi-community-samples/builds/45694173) on this pull request I'm afraid. Please have a look.

**Comment by joshcoen** [comment]
@hartsock A few pep8 errors, should be good now.

**Comment by hartsock** [comment]
Thanks for the contribution!

**Pull request merged**
