### PR TITLE
Sample code to show how to export Virtual Machine to OVF

### PR DESCRIPTION
**Pull request by jm66**
* Creates lease, download files and generates a basic OVF descriptor
* Keeps alive HTTP NFC Lease & Keeps track of export progress (kind of)

### CODE REVIEW

**Comment by prziborowski** [comment]
@SudarshanSudie The '*' should be replaced with the host.
Try making the change such as:
```
--- a/samples/export_vm.py
+++ b/samples/export_vm.py
@@ -236,12 +236,12 @@ def main():

                     temp_target_disk = os.path.join(target_directory,
                                                     deviceUrl.targetId)
-                    print 'Downloading {} to {}'.format(deviceUrl.url,
-                                                        temp_target_disk)
+                    url = deviceUrl.url.replace('*', args.host)
+                    print 'Downloading {} to {}'.format(url, temp_target_disk)
                     current_bytes_written = download_device(
                         headers=headers, cookies=cookies,
                         temp_target_disk=temp_target_disk,
-                        device_url=deviceUrl.url,
+                        device_url=url,
                         lease_updater=lease_updater,
                         total_bytes_written=total_bytes_written,
                         total_bytes_to_write=total_bytes_to_write)
```

**Comment by SudarshanSudie** [comment]
@prziborowski Thank you so much , I got that figured out and have the VMDK's on my side , so my doubt being , does compressing the vmdks before transferring to the local side possible? 
(Assuming am okay with time trade off instead of space tradeoff.)

**Comment by SudarshanSudie** [comment]
@prziborowski Also , a normal export of a VM (2 disks , 2 GB each) through the UI takes about 10 minutes but using the pyvmomi sample export_vm.py , the same vm disks take about 3 hours atleast , any idea as to why this could happen ? The network bandwidth is the same in both these cases. I am thinking HTTPLease is slowing it down, is there a different way to do this to make it as fast as the export done through UI?

**Comment by SudarshanSudie** [comment]
I was thinking a simple export and store the exported disks on the hosts side and simply scp it to our side , as this reduces downtime of the vm under consideration. Could you give me more insight on the coding part of it ?

**Comment by SudarshanSudie** [comment]
@prziborowski not setting stream in response.get and by increasing the block size to a higher number solved the issue of slow transfer.

**Pull request merged**
