### PR TITLE
make it py3 ready

### PR DESCRIPTION
**Pull request by pathcl**
Since python2 will run out of life https://pythonclock.org/ probably is a good idea to start making all these samples ready for the future :)

### CODE REVIEW

**Comment by pgbidkar** [comment]
Hi @pathcl , thanks for making changes. Please can you fix precheckin failures?

**Comment by pathcl** [comment]
Sure thing! :)

**Comment by pathcl** [comment]
I noticed this:
```
$ pycodestyle .
./add_disk_to_vm.py:92:9: E117 over-indented
./add_raw_disk_to_vm.py:81:9: E117 over-indented
./add_vm_extra_config_tags.py:43:1: E305 expected 2 blank lines after class or function definition, found 1
./cdrom_vm.py:148:1: E305 expected 2 blank lines after class or function definition, found 1
./change_vm_cd_backend.py:127:1: E305 expected 2 blank lines after class or function definition, found 1
./change_vm_nic_state.py:122:1: E305 expected 2 blank lines after class or function definition, found 1
./change_vm_vif.py:127:1: E305 expected 2 blank lines after class or function definition, found 1
./clone_vm.py:87:80: E501 line too long (94 > 79 characters)
./clone_vm.py:205:9: E722 do not use bare 'except'
./create_folder_in_datacenter.py:91:1: E305 expected 2 blank lines after class or function definition, found 1
./delete_nic_from_vm.py:137:1: E305 expected 2 blank lines after class or function definition, found 1
./deploy_ova.py:59:5: E722 do not use bare 'except'
./deploy_ova.py:170:9: E722 do not use bare 'except'
./deploy_ova.py:187:9: E722 do not use bare 'except'
./deploy_ova.py:316:9: E722 do not use bare 'except'
./deploy_ovf.py:103:13: E722 do not use bare 'except'
./deploy_ovf.py:170:9: E722 do not use bare 'except'
./deploy_ovf.py:182:5: E722 do not use bare 'except'
./deploy_ovf.py:217:1: E305 expected 2 blank lines after class or function definition, found 1
./destroy_vm.py:71:1: E305 expected 2 blank lines after class or function definition, found 1
./esxi_perf_sample.py:110:1: E305 expected 2 blank lines after class or function definition, found 1
./execute_program_in_vm.py:155:1: E305 expected 2 blank lines after class or function definition, found 1
./export_vm.py:296:1: E305 expected 2 blank lines after class or function definition, found 1
./find_by_uuid.py:62:1: E305 expected 2 blank lines after class or function definition, found 1
./generate_html5_console.py:117:1: E305 expected 2 blank lines after class or function definition, found 1
./get_vm_names.py:85:1: E305 expected 2 blank lines after class or function definition, found 1
./getorphanedvms.py:273:1: E305 expected 2 blank lines after class or function definition, found 1
./getvmsbycluster.py:154:1: E305 expected 2 blank lines after class or function definition, found 1
./getvnicinfo.py:75:17: E722 do not use bare 'except'
./getvnicinfo.py:133:1: E305 expected 2 blank lines after class or function definition, found 1
./hello_world_vcenter.py:103:1: E305 expected 2 blank lines after class or function definition, found 1
./hello_world_vcenter_with_yaml_recorder.py:110:1: E305 expected 2 blank lines after class or function definition, found 1
./linked_clone.py:153:1: E305 expected 2 blank lines after class or function definition, found 1
./list_datastore_cluster.py:87:1: E305 expected 2 blank lines after class or function definition, found 1
./list_datastore_info.py:174:1: E305 expected 2 blank lines after class or function definition, found 1
./list_dc_datastore_info.py:104:1: E305 expected 2 blank lines after class or function definition, found 1
./list_vmwaretools_status.py:92:1: E305 expected 2 blank lines after class or function definition, found 1
./reconfigure_host_for_ha.py:102:1: E305 expected 2 blank lines after class or function definition, found 1
./relocate_events.py:79:1: E305 expected 2 blank lines after class or function definition, found 1
./renamer.py:75:1: E305 expected 2 blank lines after class or function definition, found 1
./set_note.py:41:1: E305 expected 2 blank lines after class or function definition, found 1
./set_vm_storage_policy.py:48:80: E501 line too long (83 > 79 characters)
./snapshot_operations.py:191:1: E305 expected 2 blank lines after class or function definition, found 1
./soft_reboot.py:30:1: E305 expected 2 blank lines after class or function definition, found 1
./update_esxi_advanced_settings.py:135:1: E305 expected 2 blank lines after class or function definition, found 1
./upload_file_to_vm.py:115:1: E305 expected 2 blank lines after class or function definition, found 1
./vSphereAutoRestartManager.py:95:1: E305 expected 2 blank lines after class or function definition, found 1
./vcenter_details.py:83:1: E305 expected 2 blank lines after class or function definition, found 1
./virtual_machine_device_info.py:204:1: E305 expected 2 blank lines after class or function definition, found 1
./virtual_machine_device_info.py:267:13: E117 over-indented
./vminfo_quick.py:38:1: E305 expected 2 blank lines after class or function definition, found 1
./tests/interactive_wrapper_tests.py:21:9: E731 do not assign a lambda expression, use a def
./tests/interactive_wrapper_tests.py:23:9: E731 do not assign a lambda expression, use a def
./tests/interactive_wrapper_tests.py:27:9: E731 do not assign a lambda expression, use a def
./tests/interactive_wrapper_tests.py:33:9: E731 do not assign a lambda expression, use a def
./tests/interactive_wrapper_tests.py:35:9: E731 do not assign a lambda expression, use a def
./tests/interactive_wrapper_tests.py:37:9: E731 do not assign a lambda expression, use a def
./tests/interactive_wrapper_tests.py:39:9: E731 do not assign a lambda expression, use a def
./tests/interactive_wrapper_tests.py:43:9: E731 do not assign a lambda expression, use a def
./tests/interactive_wrapper_tests.py:97:9: E731 do not assign a lambda expression, use a def
./tests/interactive_wrapper_tests.py:99:9: E731 do not assign a lambda expression, use a def
./tools/datacenter.py:25:56: W605 invalid escape sequence '\)'
./tools/datacenter.py:55:1: E305 expected 2 blank lines after class or function definition, found 1
```

Will also fix them

**Comment by pgbidkar** [comment]
LGTM
@kumahesh , please review this.

Thanks

**Comment by pathcl** [comment]
Yeah I will! I made a mistake here by using 2to3 will fix it and push
changes along with travis errors

Best,

**Comment by pathcl** [comment]
Will close this pr until I fix everything for py3

**Pull request closed without merging**
